#!/usr/bin/env bash

# Ignore shellcheck case SC2086
# shellcheck disable=SC2086

# Function to audit subdomains
audit_subdomain() {
    local domain=$1
    local subdomain=$2
    local record

    record=$(dig +short $subdomain.$domain)
    record_type=$(dig +short -t A $subdomain.$domain)

    if [[ -z "$record" ]]; then
        echo "No record found for $subdomain.$domain"
    elif [[ -n "$record_type" ]]; then
        echo "The subdomain $subdomain.$domain is an A record and points to $record"
    else
        record_type=$(dig +short -t CNAME $subdomain.$domain)
        echo "The subdomain $subdomain.$domain is a CNAME record and points to $record"
    fi
}

# Check if domain argument is provided
if [[ -z "$1" ]]; then
    echo "Error: domain name is mandatory"
    exit 1
else
    domain=$1
fi

# Check if subdomain argument is provided
if [[ -n "$2" ]]; then
    subdomain=$2
    audit_subdomain $domain $subdomain
else
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        audit_subdomain $domain $subdomain
    done
fi
